#include "testlib.hpp"
#include "utils.hpp"

#include <exception>
#include <iostream>


// Used for consistency
#define TEST_NAME @FUNC_NAME@


// Forward declare tests
int TEST_NAME();

/** Catch and print an error before exiting */
#define CATCH_ERROR(ERROR)                                                                        \
    catch (const ERROR &e) {                                                                      \
        std::cout << #ERROR ": " << e.what() << std::endl;                                        \
        return -1;                                                                                \
    }

/** main */
int main() {
    try {
        return TEST_NAME();
    }
    CATCH_ERROR(UnitTest::TestLib::Error)
    CATCH_ERROR(Utils::Error::Unexpected::Base)
    CATCH_ERROR(Utils::Error::Python::Base)
    CATCH_ERROR(Utils::Error::Claricpp)
    CATCH_ERROR(std::exception)
}
